services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1@sha256:dea26401d06341095cc4ea9d66896200b55de5ca1daa1d2fcbe58493afa6e0ad
    volumes:
      - ${PWD}/src/theme:/opt/keycloak/themes
      - ${PWD}/realms:/opt/keycloak/data/import:ro
    command:
      - start-dev
      - --import-realm
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
    ports:
      - 8080:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=dev_only
      - KC_LOG_LEVEL=info,at.worlddirect:trace
