services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.4@sha256:ae8efb0d218d8921334b03a2dbee7069a0b868240691c50a3ffc9f42fabba8b4
    volumes:
      - ${PWD}/src/theme:/opt/keycloak/themes
      - ${PWD}/realms:/opt/keycloak/data/import:ro
    command:
      - start-dev
      - --import-realm
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
    ports:
      - 8080:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=dev_only
      - KC_LOG_LEVEL=info,at.worlddirect:trace
