#!/usr/bin/env bash
#
# Refreshes the bundled upstream community translations of this theme.
#
# RHBK is built with -DskipCommunityTranslations and therefore ships only 'en';
# all other locales must be bundled with the custom theme itself (see README.md,
# section "Internationalization (RHBK vs. Keycloak)").
#
# Usage: scripts/update-translations.sh [<upstream-keycloak-version>]
#
# Without an argument, the version is taken from the image tag in compose.yaml.
# The upstream version corresponding to an RHBK release is its version without
# the .redhat-NNNNN suffix (e.g. RHBK 26.6.4.redhat-00001 -> upstream 26.6.4).
set -euo pipefail

cd "$(dirname "$0")/.."

LOCALES="de"
MESSAGES_DIR="src/theme/keycloak-theme-world-direct-base/login/messages"
OVERRIDES_MARKER="# --- World-Direct overrides"

version="${1:-$(grep -oE 'keycloak/keycloak:[0-9]+\.[0-9]+\.[0-9]+' compose.yaml | cut -d: -f2)}"
if [ -z "$version" ]; then
    echo "error: could not determine Keycloak version (pass it as argument)" >&2
    exit 1
fi

for locale in $LOCALES; do
    file="${MESSAGES_DIR}/messages_${locale}.properties"
    url="https://raw.githubusercontent.com/keycloak/keycloak/${version}/themes/src/main/resources-community/theme/base/login/messages/messages_${locale}.properties"

    if ! grep -q "^${OVERRIDES_MARKER}" "$file"; then
        echo "error: overrides marker '${OVERRIDES_MARKER}' not found in ${file}" >&2
        exit 1
    fi
    overrides="$(sed -n "/^${OVERRIDES_MARKER}/,\$p" "$file")"

    upstream="$(curl -fsSL "$url")"

    {
        printf '# Generated by scripts/update-translations.sh -- do not edit the upstream part by hand.\n'
        printf '#\n'
        printf '# Upstream community translations (Keycloak %s), required because RHBK is\n' "$version"
        printf '# built with -DskipCommunityTranslations and ships only English.\n'
        printf '# Source: %s\n' "$url"
        printf '%s\n' "$upstream"
        printf '\n# -----------------------------------------------------------------------------\n'
        printf '%s\n' "$overrides"
    } > "$file"

    echo "updated ${file}: Keycloak ${version}, $(grep -cE '^[^#]+=' "$file") keys"
done
